//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodPin {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FoodPin.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        public static string RateUs {
            get {
                return ResourceManager.GetString("RateUs", resourceCulture);
            }
        }
        
        public static string TellTheFeedback {
            get {
                return ResourceManager.GetString("TellTheFeedback", resourceCulture);
            }
        }
        
        public static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        public static string UndoCheckIn {
            get {
                return ResourceManager.GetString("UndoCheckIn", resourceCulture);
            }
        }
        
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string SearchRestaurants {
            get {
                return ResourceManager.GetString("SearchRestaurants", resourceCulture);
            }
        }
        
        public static string NewRestaurantTitle {
            get {
                return ResourceManager.GetString("NewRestaurantTitle", resourceCulture);
            }
        }
        
        public static string RestaurantNameLabel {
            get {
                return ResourceManager.GetString("RestaurantNameLabel", resourceCulture);
            }
        }
        
        public static string RestaurantTypeLabel {
            get {
                return ResourceManager.GetString("RestaurantTypeLabel", resourceCulture);
            }
        }
        
        public static string RestaurantAddressLabel {
            get {
                return ResourceManager.GetString("RestaurantAddressLabel", resourceCulture);
            }
        }
        
        public static string RestaurantPhoneLabel {
            get {
                return ResourceManager.GetString("RestaurantPhoneLabel", resourceCulture);
            }
        }
        
        public static string RestaurantDescriptionLabel {
            get {
                return ResourceManager.GetString("RestaurantDescriptionLabel", resourceCulture);
            }
        }
        
        public static string RestaurantNameTextFieldPlaceholder {
            get {
                return ResourceManager.GetString("RestaurantNameTextFieldPlaceholder", resourceCulture);
            }
        }
        
        public static string RestaurantTypeTextFieldPlaceholder {
            get {
                return ResourceManager.GetString("RestaurantTypeTextFieldPlaceholder", resourceCulture);
            }
        }
        
        public static string RestaurantAddressTextFieldPlaceholder {
            get {
                return ResourceManager.GetString("RestaurantAddressTextFieldPlaceholder", resourceCulture);
            }
        }
        
        public static string RestaurantPhoneTextFieldPlaceholder {
            get {
                return ResourceManager.GetString("RestaurantPhoneTextFieldPlaceholder", resourceCulture);
            }
        }
        
        public static string RestaurantDescriptionTextViewPlaceholder {
            get {
                return ResourceManager.GetString("RestaurantDescriptionTextViewPlaceholder", resourceCulture);
            }
        }
        
        public static string NumbersOnlyWarning {
            get {
                return ResourceManager.GetString("NumbersOnlyWarning", resourceCulture);
            }
        }
        
        public static string AddedRestaurantWarning {
            get {
                return ResourceManager.GetString("AddedRestaurantWarning", resourceCulture);
            }
        }
        
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        public static string EmptyFieldsWarning {
            get {
                return ResourceManager.GetString("EmptyFieldsWarning", resourceCulture);
            }
        }
        
        public static string ChoosingPhotoSource {
            get {
                return ResourceManager.GetString("ChoosingPhotoSource", resourceCulture);
            }
        }
        
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        public static string PhotoLibrary {
            get {
                return ResourceManager.GetString("PhotoLibrary", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string CheckInWarning {
            get {
                return ResourceManager.GetString("CheckInWarning", resourceCulture);
            }
        }
    }
}
